version: '3.8'

services:
  mashgin-main-database:
    image: postgres
    restart: always
    container_name: mashgin-main-database
    environment:
      POSTGRES_DB: 'mashgin'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: '12345678'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - ./data/db:/var/lib/postgresql/data
